---
title: "Sobre o Projeto"
description: |
  Conheça mais sobre a equipe e os objetivos do Encontros com a Estatística.
output: distill::distill_article
---

# Bem-vindo(a)!

Este portal é um espaço dedicado a desmistificar a Estatística e mostrar como ela é fundamental para entender problemas reais e tomar decisões inteligentes, tanto no setor público quanto no privado.

Nosso objetivo é criar uma ponte entre a UFJF e você — seja você aluno, professor, gestor ou profissional da região de Juiz de Fora . Queremos transformar o conhecimento produzido no Departamento de Estatística em ferramentas práticas que atendam às necessidades da nossa comunidade.

### O que você encontra aqui:

- Divulgação Científica e Extensão: Conheça os projetos e aplicações desenvolvidos por nossos professores e alunos.

- Apoio à Decisão: Explore como metodologias estatísticas modernas podem ser aplicadas para identificar padrões e otimizar processos em empresas e órgãos públicos.

- Interdisciplinaridade: Discussões sobre como a análise de dados se aplica a diversas áreas do conhecimento, da saúde à engenharia.

- Canal Aberto: Um espaço de comunicação para ouvirmos suas demandas e desenvolvermos, juntos, novas soluções e ferramentas.

### Nossas Frentes de Atuação:

- Capacitação e Disseminação: Técnicas e métodos estatísticos explicados para estudantes de graduação, pós-graduação e profissionais do mercado.

- Eventos e Intercâmbio: Realização de Seminários Regionais para debater as tendências e o futuro da ciência de dados e da estatística.

- Consultoria e Parcerias: Informações sobre como o Departamento de Estatística pode colaborar com a comunidade acadêmica externa e empresas locais.

- Nosso compromisso é estabelecer um laço permanente com você, evoluindo nossas metodologias de acordo com os desafios que o mundo real apresenta.
